Repository generous-folks/reason-ui, pull requests merged in 2020-02, with the labels that each got.

#2 chore(actions): setup storybook build
  .github/workflows/main.yml
  README.md
  docs/favicon.ico
  docs/iframe.html
  docs/index.html
  docs/main.15298a5db85d78556ed8.bundle.js
  docs/main.15298a5db85d78556ed8.bundle.js.map
  docs/main.902b3b6323a4c3188c01.bundle.js
  docs/runtime~main.15298a5db85d78556ed8.bundle.js
  docs/runtime~main.15298a5db85d78556ed8.bundle.js.map
  docs/runtime~main.6b70b35614cf83eab770.bundle.js
  docs/sb_dll/storybook_ui-manifest.json
  docs/sb_dll/storybook_ui_dll.LICENCE
  docs/sb_dll/storybook_ui_dll.js
  docs/vendors~main.15298a5db85d78556ed8.bundle.js
  docs/vendors~main.15298a5db85d78556ed8.bundle.js.LICENSE.txt
  docs/vendors~main.15298a5db85d78556ed8.bundle.js.map
  docs/vendors~main.659d6ad0ddd2521734a4.bundle.js
  package.json
Labels: documentation, enhancement

#1 feat(input): enhance with more props support
  .gitignore
  src/TextInput/TextInput.re
Labels: enhancement, wip

#5 feat(theme): add theming solution
  src/Button/Button.re
  src/Button/ButtonStyles.re
  src/Code/Code.re
  src/Theme/Theme.re
  src/Theme/ThemeContext.re
  src/Theme/ThemeContextProvider.re
  src/Theme/ThemeProvider.re
  src/Theme/ThemeTypes.re
  src/Typography/Typography.re
  src/Typography/TypographyStyles.re
  stories/ButtonShowcase.re
  stories/TypographyShowcase.re
Labels: ReviewNeeded, enhancement

#8 fix(button): using button component again in story
  src/Button/ButtonStyles.re
  stories/ButtonShowcase.re
Labels: ReviewNeeded
